name: extended_image
version: 6.2.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  extended_image_library: ^3.3.0
  flutter:
    sdk: flutter
  meta: ^1.7.0
